version: '3.8'

services:
  postgres:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "developer@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "password"
    ports:
      - "80:80"
    depends_on:
      - postgres
  
  react:
    image: node:12-alpine
    #build: ./../front-end/
    volumes:
      - ./../front-end/:/app
    working_dir: /app
    ports:
      - ${FRONTEND_LOCAL_PORT}:3000
    command: npm start
    depends_on:
      - node

  node:
    image: node:12-alpine
    volumes:
      - ./../back-end/:/app
    working_dir: /app
    ports:
      - 3030:3030
    environment:
      - DATABASE_HOST=${DATABASE_HOST}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    command: npm run docker-start-dev
    depends_on:
      - postgres